// Paste your deployed Google Apps Script Web App URL here.
const API_URL = "PASTE_YOUR_APPS_SCRIPT_WEB_APP_URL_HERE";
let operatorKey = sessionStorage.getItem("operatorKey") || "";
let events = [];
const $=id=>document.getElementById(id);
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const fmt=s=>new Date(s).toLocaleString(undefined,{weekday:'long',month:'long',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'});
async function api(action,data={}){if(API_URL.includes("PASTE_"))throw new Error("Set API_URL in app.js first.");const r=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,...data,operatorKey})});const j=await r.json();if(!j.ok)throw new Error(j.error||'Request failed');return j;}
async function load(){try{const j=await api('getPublicData');events=j.events||[];render();renderNotices(j.announcements||[])}catch(e){$('events').innerHTML='<p>Unable to load the board. Check the Apps Script URL.</p>';console.error(e)}}
function render(){const upcoming=events.filter(e=>new Date(e.date)>=new Date()).sort((a,b)=>new Date(a.date)-new Date(b.date));$('eventCount').textContent=upcoming.length;if(!upcoming.length){$('events').innerHTML='<div class="card"><p>No upcoming projects yet. Check back soon.</p></div>';return}$('events').innerHTML=upcoming.map(e=>`<article class="event"><div class="date">${fmt(e.date)}</div><h3>${esc(e.name)}</h3><p class="place">📍 ${esc(e.place)}</p><p>${esc(e.description)}</p><div class="confirmed"><strong>${e.confirmed||0}${e.capacity?` / ${e.capacity}`:''} confirmed</strong><button onclick="openSignup('${esc(e.id)}')">Sign Up</button></div></article>`).join('')}
function renderNotices(ns){$('noticeArea').innerHTML=ns.slice(0,5).map(n=>`<article class="notice"><b>${esc(n.title)}</b><div>${esc(n.body)}</div><small>${n.createdAt?fmt(n.createdAt):''}</small></article>`).join('')}
function openSignup(id){const e=events.find(x=>x.id===id);if(!e)return;$('signupTitle').textContent=e.name;$('signupDetails').textContent=`${fmt(e.date)} • ${e.place}`;$('signupForm').dataset.id=id;$('signupModal').classList.remove('hidden')}
function closeModal(){$('signupModal').classList.add('hidden');$('signupForm').reset();$('signupMsg').textContent=''}
function closeOperator(){$('operatorModal').classList.add('hidden')}
$('operatorBtn').onclick=()=>{$('operatorKey').value=operatorKey;$('operatorModal').classList.remove('hidden')};
$('operatorForm').onsubmit=async e=>{e.preventDefault();operatorKey=$('operatorKey').value;sessionStorage.setItem('operatorKey',operatorKey);try{await api('operatorCheck');closeOperator();$('admin').classList.remove('hidden');await loadAdmin()}catch(err){$('operatorMsg').textContent=err.message;sessionStorage.removeItem('operatorKey');operatorKey=''}};
$('signupForm').onsubmit=async e=>{e.preventDefault();try{await api('signup',{eventId:e.target.dataset.id,parent:$('parent').value.trim(),child:$('child').value.trim(),email:$('email').value.trim(),phone:$('phone').value.trim()});$('signupMsg').textContent='You are confirmed! Thank you for serving the community.';await load();setTimeout(closeModal,900)}catch(err){$('signupMsg').textContent=err.message}};
$('eventForm').onsubmit=async e=>{e.preventDefault();try{await api('addEvent',{name:$('name').value.trim(),description:$('description').value.trim(),place:$('place').value.trim(),date:$('date').value,capacity:$('capacity').value});$('eventMsg').textContent='Event posted.';e.target.reset();await load();await loadAdmin()}catch(err){$('eventMsg').textContent=err.message}};
$('noticeForm').onsubmit=async e=>{e.preventDefault();try{await api('addAnnouncement',{title:$('noticeTitle').value.trim(),body:$('noticeBody').value.trim()});$('noticeMsg').textContent='Notification posted.';e.target.reset();await load()}catch(err){$('noticeMsg').textContent=err.message}};
async function loadAdmin(){if(!operatorKey)return;try{const j=await api('getSignups');$('signups').innerHTML=(j.signups||[]).length?j.signups.map((s,i)=>`<div><b>${esc(s.child)}</b> — ${esc(s.parent)} · ${esc(s.event)} · ${esc(s.email)} ${s.phone?`· ${esc(s.phone)}`:''}</div>`).join('<hr>'):'No signups yet.'}catch(e){$('signups').textContent=e.message}}
if(operatorKey){$('admin').classList.remove('hidden');loadAdmin()}load();
